### ISSUE TITLE
Story doesn't cover the whole screen on android

### ISSUE THREAD

**Issue by AlekseyP18** [birdwingo/react-native-instagram-stories#107]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@birdwingo/react-native-instagram-stories@1.3.4` for the project I'm working on.

The problem is only on android platform. The story screen doesn't cover the whole screen with status bar and navigation

So it looks like this
<img width="320" alt="Screenshot 2024-08-07 at 16 43 39" src="https://github.com/user-attachments/assets/056d4792-46b5-4b5f-9ea5-4cd2bc2495d7">

After my fix it's like

<img width="407" alt="Screenshot 2024-08-08 at 09 11 10" src="https://github.com/user-attachments/assets/13546649-22aa-44de-a491-370c2380be84">

Please create a small fix to solve this problem. Thanks!

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@birdwingo/react-native-instagram-stories/src/components/Modal/index.tsx b/node_modules/@birdwingo/react-native-instagram-stories/src/components/Modal/index.tsx
index 873c3b9..56dce43 100644
--- a/node_modules/@birdwingo/react-native-instagram-stories/src/components/Modal/index.tsx
+++ b/node_modules/@birdwingo/react-native-instagram-stories/src/components/Modal/index.tsx
@@ -453,7 +453,7 @@ const StoryModal = forwardRef<StoryModalPublicMethods, StoryModalProps>( ( {
   );
 
-    <Modal visible={visible} transparent animationType="none" testID="storyRNModal" onRequestClose={onClose}>
+    <Modal visible={visible} statusBarTranslucent transparent animationType="none" testID="storyRNModal" onRequestClose={onClose}>

diff --git a/node_modules/@birdwingo/react-native-instagram-stories/src/core/constants/index.ts b/node_modules/@birdwingo/react-native-instagram-stories/src/core/constants/index.ts
index 4ea5850..d36284d 100644
--- a/node_modules/@birdwingo/react-native-instagram-stories/src/core/constants/index.ts
+++ b/node_modules/@birdwingo/react-native-instagram-stories/src/core/constants/index.ts

-export const { width: WIDTH, height: HEIGHT } = Dimensions.get( 'window' );
+export const { width: WIDTH, height: HEIGHT } = Dimensions.get( 'screen' ); 
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by AlekseyP18** [comment]
The ts is throwing error for import in the following file - components/Image/index.tsx

import { StoryItemProps } from '~/core/dto/instagramStoriesDTO'; => import { StoryItemProps } from '../../core/dto/instagramStoriesDTO';

could you fix it also please

**Comment by ParthSST** [comment]
Still having the same issue in version 1.3.12

**Comment by geertvansoest** [comment]
Had the same issue after upgrading React Native and some other packages. Set `statusBarTranslucent={true}` fixed it for several devices (simulators), for example Pixel 9 Pro (API 36.0). 

But I was wondering if we don't have to also set `navigationBarTranslucent={true}` to make sure the bottom bar is hidden on all devices and versions, as mentioned in the docs for this package: https://github.com/zoontek/react-native-edge-to-edge?tab=readme-ov-file#modal-component-quirks. Does anyone know?

**Comment by geertvansoest** [comment]
**Update:** The missing of `navigationBarTranslucent={true}` may indeed occur a "gap" at the bottom of the stories modal at older Android versions, for example Android 14 (API 34):

<img width="539" height="203" alt="Image" src="https://github.com/user-attachments/assets/fa98c06b-b0f9-4eb8-a592-2b525f917c60" />

I fixed this in our project with a small patch so both `translucent` props having the same value:

```patch
diff --git a/node_modules/@birdwingo/react-native-instagram-stories/src/components/Modal/index.tsx b/node_modules/@birdwingo/react-native-instagram-stories/src/components/Modal/index.tsx
index fdcde31..fac28a2 100644
--- a/node_modules/@birdwingo/react-native-instagram-stories/src/components/Modal/index.tsx
+++ b/node_modules/@birdwingo/react-native-instagram-stories/src/components/Modal/index.tsx
@@ -460,7 +460,7 @@ const StoryModal = forwardRef<StoryModalPublicMethods, StoryModalProps>( ( {
   );
 
   return (
-    <Modal statusBarTranslucent={statusBarTranslucent} visible={visible} transparent animationType="none" testID="storyRNModal" onRequestClose={onClose}>
+    <Modal statusBarTranslucent={statusBarTranslucent} navigationBarTranslucent={statusBarTranslucent} visible={visible} transparent animationType="none" testID="storyRNModal" onRequestClose={onClose}>
       <GestureHandler onGestureEvent={onGestureEvent}>
         <Animated.View style={ModalStyles.container} testID="storyModal">
           <Pressable
```
