### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by ahsanbhatti98** [birdwingo/react-native-instagram-stories#12]
When one user stories completes and it jump on to next story. Progress bar won't work properly also when we go back from user2 to user1 stories progress bar doesn't works it stucks.

**Comment by LukasFridmansky** [comment]
Hello, thank you for using our library. First of all, do you use latest version of library? If so, can you explain the problem more in details? Is the problem on iOS or android? Thank you

**Comment by ahsanbhatti98** [comment]
Yes i am using new one

**Comment by ahsanbhatti98** [comment]
"@birdwingo/react-native-instagram-stories": "^1.0.7",
"react": "17.0.2",
"react-native": "0.68.2",
  "react-native-svg": "^13.4.0",
   "react-native-gesture-handler": "^2.4.2",
       "react-native-reanimated": "^3.2.0",

**Comment by ahsanbhatti98** [comment]
Uploading RPReplay_Final1699018088.MP4…

**Comment by ahsanbhatti98** [comment]
![IMG_F9F3E400C7A0-1](https://github.com/birdwingo/react-native-instagram-stories/assets/49521234/ad03d704-38cd-41f6-a174-08d2027722fe)

**Comment by ahsanbhatti98** [comment]
[https://go.wetransfer.com/t-FUvv6rCOV6](url)

as you can see in this video link

**Comment by ahsanbhatti98** [comment]
https://go.wetransfer.com/t-FUvv6rCOV6
as you can see in this video link

**Comment by ahsanbhatti98** [comment]
https://github.com/birdwingo/react-native-instagram-stories/assets/49521234/d24475c2-fbf5-4741-b7dc-00d729dae9cf

**Comment by michelecocuccio** [comment]
Same ISSUE here, on IOS. I still need to test it on Android. Using the latest version of the library (1.0.7) and

>     "react-native": " 0.72.6",
>     "react-native-svg": "^13.14.0",
>      "react-native-reanimated": "~3.5.4",
>      "react-native-gesture-handler": "^2.13.4",

![Simulator Screen Recording - iPhone 14 Pro - 2023-11-08 at 18 26 03](https://github.com/birdwingo/react-native-instagram-stories/assets/8071249/4a2e5daa-2386-4504-9530-60166ceba847)

**Comment by Lipo11** [comment]
please update to version 1.0.9 and if something is broken create a new issue
