### ISSUE TITLE
Stories Data from server api gives error.

### ISSUE THREAD

**Issue by ahsanbhatti98** [birdwingo/react-native-instagram-stories#13]
When i get data from my api and save it in to state. First user stories are working fine but when it goes to the next user stories it gives me this error 

 ERROR  ReanimatedError: undefined is not an object (evaluating 'userStories[newStoryIndex + 1]'), js engine: reanimated
![IMG_94E4040D62FC-1](https://github.com/birdwingo/react-native-instagram-stories/assets/49521234/17b9cf01-50b1-475a-9743-d88e56909dda)

**Comment by Lipo11** [comment]
Hello! Without exact data you received from backend we cannot help! Please describe issues more carefully. Thanks.

**Comment by ahsanbhatti98** [comment]
`const getAllStories = async () => {
    try {
      const res = await getStories();
      const responseData = res?.data?.data;
      const array = responseData?.map((item) => {
        const storyArray = item.stories?.map((storyItem) => ({
          id: storyItem?._id?.toString(),
          sourceUrl: storyItem?.mediaPaths[0]?.path
            ? storyItem?.mediaPaths[0]?.path
            : "https://images.unsplash.com/photo-1525609004556-c46c7d6cf023?auto=format&fit=crop&q=60&w=800&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Y2Fyc3xlbnwwfHwwfHx8MA%3D%3D",
          mediaType: storyItem.mediaPaths?.[0]?.mimetype?.includes("video")
            ? "video"
            : "image",
          // renderContent: () =>
          //   StoryContainer({
          //     storyData: {
          //       id: storyItem?._id || null,
          //       media: storyItem?.mediaPaths[0]?.path ? true : false,
          //       text: storyItem?.text || null,
          //       color: storyItem?.color || null,
          //       ownStory: storyItem?.ownStory || null,
          //     },
          //   }),
        }));
        return {
          id: item?.userDetail?._id?.toString(),
          name: item?.userDetail?.fullName,
          imgUrl: item?.userDetail?.dp?.path,
          stories: storyArray,
        };
      });

      // console.log("Array===>", array[1]);

      setStroyData(array);
    } catch (err) {
      console.log("Stories-Error", err);
    }
  };
  
   useEffect(() => {
    getAllStories();
  }, []);`
  this is my code

**Comment by ahsanbhatti98** [comment]
and this is what it is returning from server.

 ```
[
  {
    id: "6529bc5917f205a0193a3f01",
    imgUrl:
      "https://geelink-bucket.s3.us-east-2.amazonaws.com/251039900040426871697234049896image.jpg",
    name: "Drim",
    stories: [
      {
        id: "65439be574fdd1bb0f1768fb",
        mediaType: "image",
        sourceUrl:
          "https://geelink-bucket.s3.us-east-2.amazonaws.com/108587092155837171698929636193image.jpg",
      },
      {
        id: "65439bee74fdd1bb0f1768fc",
        mediaType: "image",
        sourceUrl:
          "https://geelink-bucket.s3.us-east-2.amazonaws.com/108587092155837171698929636193image.jpg",
      },
      {
        id: "65439c7c74fdd1bb0f1768fe",
        mediaType: "video",
        sourceUrl:
          "https://geelink-bucket.s3.us-east-2.amazonaws.com/78068398744817441698929785878video.mp4",
      },
      {
        id: "6543bd9874fdd1bb0f176908",
        mediaType: "image",
        sourceUrl:
          "https://geelink-bucket.s3.us-east-2.amazonaws.com/108587092155837171698929636193image.jpg",
      },
      {
        id: "6543c24174fdd1bb0f176909",
        mediaType: "image",
        sourceUrl:
          "https://geelink-bucket.s3.us-east-2.amazonaws.com/108587092155837171698929636193image.jpg",
      },
      {
        id: "6543c24174fdd1bb0f1769099999",
        mediaType: "image",
        sourceUrl:
          "https://geelink-bucket.s3.us-east-2.amazonaws.com/108587092155837171698929636193image.jpg",
      },
    ],
  },
  {
    id: "64c7dcb2425603a7c3e15c95",
    imgUrl:
      "https://geelink-bucket.s3.us-east-2.amazonaws.com/89327933720958691697239417668image.jpg",
    name: "Rock",
    stories: [
      {
        id: "6543a80074fdd1bb0f176904",
        mediaType: "image",
        sourceUrl:
          "https://geelink-bucket.s3.us-east-2.amazonaws.com/49392191326342561698932734437image.jpg",
      },
      {
        id: "6543bc2c74fdd1bb0f176907",
        mediaType: "image",
        sourceUrl:
          "https://geelink-bucket.s3.us-east-2.amazonaws.com/108587092155837171698929636193image.jpg",
      },
    ],
  },
];
```
