### ISSUE TITLE
Delete user story.

### ISSUE THREAD

**Issue by Pakile** [birdwingo/react-native-instagram-stories#15]
First and foremost, I'd like to express my deep gratitude for creating this wonderful library. It has been an invaluable resource for my React Native application, and I'm truly impressed with its functionality.

I've been using this library to display stories, and it's been a fantastic addition to my project. However, I've encountered an issue that I hope to get some help or a solution for.

My issue is that when I delete an item in the user stories (delete an item in stories of user story works fine) and call toNextStory ( I tried to use toPreviousStory or scrollTo but not work), the animated header in the library gets paused.

Is there a way to address this issue or any guidance you can provide on optimizing the animated header when deleting an item in the stories?

**Comment by LukasFridmansky** [comment]
Hello, thank you for your feedback. I will take a look on your issue and will let you know.

**Comment by Lipo11** [comment]
please update to version 1.0.9 and if something is broken create a new issue
