### ISSUE TITLE
Avatar size doesn't make the image fill the content

### ISSUE THREAD

**Issue by michelecocuccio** [birdwingo/react-native-instagram-stories#17]
Setting the prop `avatarSize={72}` doesn't make the image fill the content. Tested on IOS

<img width="363" alt="Screenshot 2023-11-08 at 18 33 34" src="https://github.com/birdwingo/react-native-instagram-stories/assets/8071249/f4eaddc0-8520-434c-96f7-50b91d2bbce8">

https://github.com/birdwingo/react-native-instagram-stories/blame/a6b7571cf43a30866685ee0cbf2ee548acb8cab4/src/components/Avatar/index.tsx#L58

> "@birdwingo/react-native-instagram-stories": "^1.0.7",
> "react-native": " 0.72.6",
> "react-native-svg": "^13.14.0",
>  "react-native-reanimated": "~3.5.4",
>  "react-native-gesture-handler": "^2.13.4",

Also, it is possibile to set a props to configure the style of the progress bar? (the background and fill color). I think it will be very useful in terms of customisation.

**Comment by LukasFridmansky** [comment]
Hello, thank you for your feedback. We will fix as soon as possible.

**Comment by michelecocuccio** [comment]
@LukasFridmansky I can see that you opened a PR for the fixes. That's great! One thing I have forgot to mention that I think you misspelled "worklet" in the main file of InstagramStories

https://github.com/birdwingo/react-native-instagram-stories/blob/a6b7571cf43a30866685ee0cbf2ee548acb8cab4/src/components/InstagramStories/index.tsx#L46

**Comment by LukasFridmansky** [comment]
Thank you, actually I have it misspelled three times, but it seems that those worklets are not even needed, but thank you for your notice anyway :)

**Comment by Lipo11** [comment]
please update to version 1.0.9 and if something is broken create a new issue
