### ISSUE TITLE
Progress bar value is not reset after changing story and video time is not calculated properly

### ISSUE THREAD

**Issue by michelecocuccio** [birdwingo/react-native-instagram-stories#21]
@LukasFridmansky thanks for the fix early. 

I think there are still issues with the progress bar, especially when using video and images together

- first of all the timer should be reset every time a story is changed which at the moment it doesn't happen
- secondly, I think the time of the video is not calculated properly as the first time it starts from the default 1000ms value

I really like the library but I think a bit more focus should put on how the progress bar work which I know is usually the most complicated thing to do. Keep the good work

![Simulator Screen Recording - iPhone 14 Pro - 2023-11-08 at 22 13 37](https://github.com/birdwingo/react-native-instagram-stories/assets/8071249/2eeebe99-3126-4d7e-84fe-45fdf290661d)

**Comment by Lipo11** [comment]
hi, this is an open source project and developing it is not easy because it is not our main goal. However, we would like to welcome new maintainers! we tried to fix that soon as possible. thanks for patience.

**Comment by Lipo11** [comment]
Hello, please try to update lib to 1.0.11 and let us know

**Comment by michelecocuccio** [comment]
Hello, thanks for the update. I think it has improved. But I still have issues especially when the stories changes with the Pan animation. If I press on the side it looks it work as intended, but if I drag it left or right sometime the progress doesn't start

DRAG ANIMATION
![Pan animation](https://github.com/birdwingo/react-native-instagram-stories/assets/8071249/ec7ac30c-25ef-4dc5-8732-93d297fca3a0)

TAP ANIMATION
![Tap animation](https://github.com/birdwingo/react-native-instagram-stories/assets/8071249/d6917eff-28b6-467c-9ce6-91e177df690a)

**Comment by Lipo11** [comment]
Added next fixes to 1.0.12, hope its fine now
