### ISSUE TITLE
Stories overlay speed

### ISSUE THREAD

**Issue by matmac** [birdwingo/react-native-instagram-stories#24]
Hello! Thanks for this awesome package!

I was wondering if there is a way we can add a property to change the speed the overlay shows.

It is rather slow and I'd like to make it appear faster.

Thanks!

**Comment by LukasFridmansky** [comment]
Hello, thank you for your feedback. I am not sure if I understood the question, but there is a property `animationDuration` with default value 10000 ms.

**Comment by Lipo11** [comment]
Added modalAnimationDuration to API
