### ISSUE TITLE
I have a higher version of react-native-reanimated "3.6.1" and I have a "version" error

### ISSUE THREAD

**Issue by adnaneghalem** [birdwingo/react-native-instagram-stories#28]
![Capture d’écran 2023-12-13 à 16 27 44](https://github.com/birdwingo/react-native-instagram-stories/assets/35136539/29cf1935-99e1-4748-8722-c0e57b109b05)

**Comment by Lipo11** [comment]
Hello! i believe this is not our problem, can you debug more and let us know which part of instagram story is the problem? it looks like you havent installed reanimated lib correctly. check this pls: https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/getting-started/ mainly the babel part.
