### ISSUE TITLE
Callback for individual stories

### ISSUE THREAD

**Issue by pkardas** [birdwingo/react-native-instagram-stories#29]
Hi, first of all, thanks for the awesome library :D

I noticed that `onShow` and `onHide` are triggered only when I open & close user (entire group of stories).

It would be cool to have a possibility to detect when a user moves to another/previous story (within user, or moves to another user), something like:

```
onStoryStart | ( userId?: string, storyId?: string ) => void
onStoryEnd | ( userId?: string, storyId?: string ) => void
```

**Comment by LukasFridmansky** [comment]
Hello, thanks for you feedback. We will add this functionality as soon as possible.

**Comment by geertvansoest** [comment]
@LukasFridmansky I see this functionality has been added recently. Unfortunately, it seems to doesn't work perfectly. If I open a story using a ref, for example `onPress={() => storiesRef.current?.show(story.id)}`, the end callback is triggered before the start callback:

Our code:
```
onStoryStart={(userId, storyId) => {
   console.log('START -', userId, storyId);
}}
onStoryEnd={(userId, storyId) => {
   console.log('END -', userId, storyId);
}}
```

Our log after opening the stories clicking on a card in our navigation list:
```
END - 486063 486068
START - 486053 486058
```

Do you know if there's a way to fix this? 

Also, if we close the stories modal by clicking the "Close" icon, after some seconds the end callback is triggered for the story that was currently playing. Is there a way to prevent this, for example to verify in the end callback if the stories modal is still open?

**Comment by geertvansoest** [comment]
@LukasFridmansky Do you have an update on this?
