### ISSUE TITLE
Center horizontal video

### ISSUE THREAD

**Issue by mezalejandro** [birdwingo/react-native-instagram-stories#34]
Hello, thanks for create this library is amazing!
I want to know if I could center a video that is not fullscreen.

Thanks again

**Comment by LukasFridmansky** [comment]
Hello, thank you for your feedback. I will check it as soon as possible.

**Comment by Lipo11** [comment]
We added imageStyles and mediaContainerStyle which allow you to modify all styles you wanted in the new release! Thanks for the patience.
