### ISSUE TITLE
Starts stories for a particular index item

### ISSUE THREAD

**Issue by gust-m** [birdwingo/react-native-instagram-stories#35]
Is there a property, like 'progressIndex,' to indicate from which story I want to start? If I have already seen the first and second stories before, I want to start from the third and beyond.

**Comment by LukasFridmansky** [comment]
Hello. Did you try saveProgress prop? It will automatically save the progress and will continue on next story.

**Comment by gust-m** [comment]
Hi Lukas, thanks for your answer. Do i need to clear async storage? I mean, to not make it lose performance by keeping unnecessary old data

**Comment by LukasFridmansky** [comment]
No need
