### ISSUE TITLE
Bug: [Reanimated] onStoryStart

### ISSUE THREAD

**Issue by gust-m** [birdwingo/react-native-instagram-stories#40]
Hi folks, im having a bug when I pass onStoryStart to props and try to go back to previous story, I was using just to print some ids, but even with empty callback it keeps crashing. To next stories it works as expected, but when u hit to previous this crash happens:

![image](https://github.com/birdwingo/react-native-instagram-stories/assets/67772723/353e5ca0-99f6-4603-a199-8ae4e83f3e0f)

**Comment by Lipo11** [comment]
Hello, try 1.2.2 and let us know, thanks for the announcement.
