### ISSUE TITLE
Animation not continued after unsuccessful `onPreviousStory` call

### ISSUE THREAD

**Issue by radovix** [birdwingo/react-native-instagram-stories#42]
If `onPreviousStory` is called on the first story (meaning that no previous story exists), progress animation will stop and not resume.

You can see the problem I described in the video below. Press events are not displayed tho.

https://github.com/birdwingo/react-native-instagram-stories/assets/32815752/311564b2-d9c0-4b02-a636-fd6968db55f7

**Comment by LukasFridmansky** [comment]
Hello, thank you, your pull request is being reviewed right now and should be merged soon.

**Comment by radovix** [comment]
No problem. I'm glad I could help and give back to community 😁
