### ISSUE TITLE
Can't manage avatar spacing and text transposition

### ISSUE THREAD

**Issue by robert-rex** [birdwingo/react-native-instagram-stories#46]
Hey guys, before, thank you for such a cool library! I can't figure out what the problem is when trying to add styles. I'm trying to use 
avatarListContainerProps={{
            contentContainerStyle: {
                paddingHorizontal: 20, 
                justifyContent: 'space-between' 
            }
          }}
to add indents between icons, but it doesn't work for some reason. I also want to do text transposition 
textStyle={{{
            flexWrap: 'wrap', 
            textAlign: 'center', 
          }}
but I also don't see the result. Is it possible that I'm doing something wrong?

**Comment by Audeos** [comment]
I couldn't do it neither. I placed marginHorizontal inside the Avatars with a patch for now.
