### ISSUE TITLE
The image does not fill the screen completely

### ISSUE THREAD

**Issue by robert-rex** [birdwingo/react-native-instagram-stories#50]
Hey guys! I'm addressing with the problem of not completely filling the screen with the image. 
This problem has been touched on before and even posted fixes to solve this problem, as I understand it. 
I have updated the library by downloading the fixes you made, but the result is the same. My image does not completely fill the screen and it looks like a handmade on the knee( 
Here is an example of my display:

![Simulator Screenshot - iPhone 15 Pro - 2024-02-21 at 17 15 25](https://github.com/birdwingo/react-native-instagram-stories/assets/1505437/11251baf-e51c-4c63-8be8-62d5318d6f8c)
![Simulator Screenshot - iPhone 15 Pro - 2024-02-21 at 17 15 41](https://github.com/birdwingo/react-native-instagram-stories/assets/1505437/79faddea-3d78-49d4-a622-45bc1d2efa9d)

**Comment by huzaifaazim0** [comment]
is it supposed to be full or according to image height to width ratio?

**Comment by LukasFridmansky** [comment]
Hey, image has default styles with aspectRatio: 0.5626, so if you want full height, you need to set in imageStyles aspectRatio : WIDTH / HEIGHT

**Comment by robertino-rex** [comment]
my image is 1920 pixels high and 1080 pixels wide. Judging by the logic of the code, by default aspectRatio: 0.5626 should be applied, filling the screen completely. But as I showed on the screens above it is applied leaving indents at the top and bottom on the iphone simulator

**Comment by robert-rex** [comment]
my image is 1920 pixels high and 1080 pixels wide. Judging by the logic of the code, by default aspectRatio: 0.5626 should be applied, filling the screen completely. But as I showed on the screens above it is applied leaving indents at the top and bottom on the iphone simulator

**Comment by LukasFridmansky** [comment]
Hey, if you need to cover full screen with image, you can use imageProps and resizeMode: 'cover'. But in that case you need also change aspectRatio as mentioned before to assure that it will cover full screen. If anything is wrong or it didn't meet your expectations, feel free to reopen issue. Thank you
