### ISSUE TITLE
How to show stories text along each story having photo or video with it ?

### ISSUE THREAD

**Issue by Ahsanali012** [birdwingo/react-native-instagram-stories#52]
Is there anyway i can pass text along each stories ?, if not please add this feature where If user is adding stories with picture or video text along it should also be added. By text i mean description . Please reply to my comment.****

**Comment by Ahsanali012** [comment]
And Custom Buttons in the bottom of the story as a like button or a text input can also be added ...

**Comment by LukasFridmansky** [comment]
Hey, I don't understand where should be text placed. But anyway, there is for each story prop renderContent and renderFooter functions. renderContent id placed through the image and renderFooter is placed under the picture. Will it solve your problem? If not please let me know.

**Comment by Ahsanali012** [comment]
> Hey, I don't understand where should be text placed. But anyway, there is for each story prop renderContent and renderFooter functions. renderContent id placed through the image and renderFooter is placed under the picture. Will it solve your problem? If not please let me know.



Can you provide me code snippet or example if i want to show the text in the middle of the story using renderContent and renderFooter example
