### ISSUE TITLE
Fix styling for long titles

### ISSUE THREAD

**Issue by geertvansoest** [birdwingo/react-native-instagram-stories#58]
To start I want to say this package is amazing! Easy to configure and works very good. 

In our project we don't "categorize" the stories by user, but by event (for example, a football match that was played recently). Because of this, the titles are more descriptive and can be quite long. If that's the case, the close icon can be moved to far to the right and also the vertical alignment is not that good.

In our project, I fixed this creating the patch below (didn't test it very well with an avatar next to the title, since we don't have those). For other projects, that also have an avatar shown in the stories modal, it could be better to add a top position to the close icon related to the avatar size (instead of vertical align it to the center).

```diff
diff --git a/node_modules/@birdwingo/react-native-instagram-stories/src/components/Header/Header.styles.ts b/node_modules/@birdwingo/react-native-instagram-stories/src/components/Header/Header.styles.ts
index e2d44a4..e873cd0 100644
--- a/node_modules/@birdwingo/react-native-instagram-stories/src/components/Header/Header.styles.ts
+++ b/node_modules/@birdwingo/react-native-instagram-stories/src/components/Header/Header.styles.ts
@@ -5,11 +5,12 @@ export default StyleSheet.create( {
     position: 'absolute',
     flexDirection: 'row',
     justifyContent: 'space-between',
-    alignItems: 'center',
+    alignItems: 'flex-start',
     left: 16,
     top: 32,
   },
   left: {
+    flex: 1,
     flexDirection: 'row',
     alignItems: 'center',
     gap: 12,
```

A before and after are below:
![image](https://github.com/birdwingo/react-native-instagram-stories/assets/6870951/de301907-c5e3-41da-a818-a692d651b8a4)

![image](https://github.com/birdwingo/react-native-instagram-stories/assets/6870951/77e086ba-9b60-4d40-b210-3c78a62b7630)

**Comment by LukasFridmansky** [comment]
Hello, you can use the newest version of library. The issue with text was fixed and you can adjust position with headerStyle property.
