### ISSUE TITLE
Feature request: property to disable "default" avatar list

### ISSUE THREAD

**Issue by geertvansoest** [birdwingo/react-native-instagram-stories#62]
In our app, we use "custom" avatars/cards to open the story modal using `InstagramStoriesPublicMethods` as a ref. The default avatar list is not visible since we didn't set the `imgUrl` property for any story.

However, even if it is not visible for the users, the ScrollView for the avatars is still rendered. Would it be possible to add a property to disable this completely? Or to only render the ScrollView if there's at least one story containing the `imgUrl`?

The related code is here:
https://github.com/birdwingo/react-native-instagram-stories/blob/main/src/components/InstagramStories/index.tsx#L210-L225

If no prop will be added, it can be automatically checked using something simple like this:
```
// Render the avatar list if at least one story has an image
const renderAvatarList: boolean = data.some(story => Boolean(story.imgUrl));
```

**Comment by LukasFridmansky** [comment]
Hello, you can use the newest version of library. There was added new property `hideAvatarList`
