### ISSUE TITLE
Adding Gradient to top of StoryList

### ISSUE THREAD

**Issue by RomainTweaks** [birdwingo/react-native-instagram-stories#65]
Hi, i really want to thank you for this lib. It's amazing and easy to use. <3

Is it possible to add to your roadmap a possibility to add a linear gradient to the top of StoryList component, juste behind the Progress, avatar and name.

I nedd this to ensure the visibility of these items when the story's images his very light and my colors are white or dark when colors are black.

I really need this.
Thanks!

**Comment by LukasFridmansky** [comment]
Hello, you can use the newest version of library. There was added property `imageOverlayView` where you can add your own component and to place anywhere you need with absolute position.
