### ISSUE TITLE
Unable to use local images 

### ISSUE THREAD

**Issue by Minte-grace** [birdwingo/react-native-instagram-stories#67]
The story image works only with hosted images I couldnt make it work with local images any solution to this?

**Comment by LukasFridmansky** [comment]
Hello, thank you for your suggestion. I will change it

**Comment by LukasFridmansky** [comment]
Hello, you can now use source property.

**Comment by Adil7767** [comment]
Still unable to use local images as userProfile image if there is no profile then i want to show default images in avatar list

**Comment by LukasFridmansky** [comment]
Hey, so you can use avatarSource now

**Comment by Adil7767** [comment]
thank you ,please mention these things to Readme or we can make a document for this library as it is amazing one library

**Comment by Adil7767** [comment]
`export const GREY_LOGO = require('../../assets/images/grey-icon.png')`

I am just getting loader not avatarSource image 
after console this thing 
`{console.log(avatarSource,'avatarSource')}`
i got
` {"GREY_LOGO": 9} avatarSource`
but when i console same thing in my component i got 
just 9
i and if i replace this line like
   `source={avatarSource?.GREY_LOGO ?? { uri: imgUrl }}`
   then image display well
   but i got a solution for you 
   if i do this showing well
`avatarSource: {src:GREY_LOGO},`
thanks again for this amazing library
