### ISSUE TITLE
Video player in story item not working

### ISSUE THREAD

**Issue by bilal1031** [birdwingo/react-native-instagram-stories#68]
There seems to be an issue when trying to add a video story, it just shows a loader and freezes after some time.

Here is some information about what I was using and what I learned after testing.

1. The video is 7 seconds long and is hosted on a cloud and it is a mp4 codec video.
2. On Android Emulators it works sometimes, but sometimes it does not.
3. On a physical device it does not work correctly

I have attached a video to better show what it is exactly doing.

https://github.com/birdwingo/react-native-instagram-stories/assets/56048741/8c4fc9a1-d8ff-49bc-8429-f72a881dfad0

**Comment by Ibrahim-Arif** [comment]
> There seems to be an issue when trying to add a video story, it just shows a loader and freezes after some time.
> 
> 
> 
> Here is some information about what I was using and what I learned after testing.
> 
> 
> 
> 1. The video is 7 seconds long and is hosted on a cloud and it is a mp4 codec video.
> 
> 2. On Android Emulators it works sometimes, but sometimes it does not.
> 
> 3. On a physical device it does not work correctly
> 
> 
> 
> I have attached a video to better show what it is exactly doing.
> 
> 
> 
> https://github.com/birdwingo/react-native-instagram-stories/assets/56048741/8c4fc9a1-d8ff-49bc-8429-f72a881dfad0
> 
> 
> 
> 

Same

**Comment by LukasFridmansky** [comment]
Hey, make sure that you have installed react-native-video package.
