### ISSUE TITLE
Pause stories

### ISSUE THREAD

**Issue by geertvansoest** [birdwingo/react-native-instagram-stories#71]
You can pause a story by pressing and keep suppressed the screen. 

When you do this, you can see videos are paused and the progress bar stops filling up. But after about 1 second, the progress bar continues to fill up even if you are still pressing the screen. I think the story must be paused as long as you're pressing the screen, like Instagram does.

Another issue is that if you release your finger videos keep paused and do not continue playing.

**Comment by gust-m** [comment]
If you slide to next story (instead just tapping) shows the same problem, the video starts paused and there is no way to unpause it
