### ISSUE TITLE
Feature request: faster animation

### ISSUE THREAD

**Issue by geertvansoest** [birdwingo/react-native-instagram-stories#72]
At this moment, when you go to the next story (from another "collection") the rotating animation is quite heavy and slow. 

Would it be possible to add a property to use a more subtle animation (for example, use the same fade animation as if you navigate to another story inside the same collection)? Or to make it at least run faster?

**Comment by LukasFridmansky** [comment]
Hello, you can use storyAnimationDuration and adjust the duration of animation.
