### ISSUE TITLE
Feature request: hide elements on pause

### ISSUE THREAD

**Issue by geertvansoest** [birdwingo/react-native-instagram-stories#73]
Would it be possible to hide elements like the progress bar when you press and hold the screen (when the story is paused)? Like Instagram does, so that users can make screenshots of specific story content.

**Comment by LukasFridmansky** [comment]
Hello, you can use hideElementsOnLongPress and set it to true.

**Comment by geertvansoest** [comment]
In the meantime, I found out this error didn't occur before we also updated the (other) packages, under which `react-native-reanimated` from 3.8.1 to 3.12.0. So I think it's also related to that new version.
