### ISSUE TITLE
Stories wont show when clicked 

### ISSUE THREAD

**Issue by Ahsanali012** [birdwingo/react-native-instagram-stories#87]
As shown in the video when i am trying to click to show the stories it keeps loading and does not show anything, I checked i have stable internet connection also changed the library version still facing this issue

https://github.com/birdwingo/react-native-instagram-stories/assets/55757950/99b6e124-182f-465d-8a80-69df801895c7

![WhatsApp Image 2024-06-28 at 7 04 09 PM](https://github.com/birdwingo/react-native-instagram-stories/assets/55757950/695fbf3f-1427-4f9e-b20b-9a40e62d1457)

**Comment by LukasFridmansky** [comment]
Hey, the issue seems to be caused by image you use. Are you sure your image is available? According to screenshot you are receiving 403 error.

**Comment by Ahsanali012** [comment]
> Hey, the issue seems to be caused by image you use. Are you sure your image is available? According to screenshot you are receiving 403 error.
<img width="811" alt="image" src="https://github.com/birdwingo/react-native-instagram-stories/assets/55757950/f5b2b83c-7fd5-47bd-84b3-b19c69aa6ffb">

Yes I am sure its available

**Comment by Ahsanali012** [comment]
This is how i am using as you can see stories will only show when status is 200 as it will have records using &&

```
  {AllStoriesPosts && AllStoriesPosts.length > 0 && (
                        <ScrollView>
                          <InstagramStories
                            avatarSize={70}
                            backgroundColor={"gray"}
                            
                            stories={InstaStories}
                            videoAnimationMaxDuration={20000}
                          />
                        </ScrollView>
                      )}
```

**Comment by LukasFridmansky** [comment]
Yeah, that is fine, but I am referring to the console warning you sent. There is a url of some image and it seems that the image is not working. And because the image was not loaded the modal was not opened.

**Comment by Ahsanali012** [comment]
Yes Thanks i saw one image was not uploaded correctly. I deleted it and now modal is opening. Can you edit the library such that if 1 story image has some issue it should not load that but other should be able to load?. Or the one who has issue loading should show some error to the user

**Comment by LukasFridmansky** [comment]
I will try, but I am not sure if it will be possible to handle such case
