### ISSUE TITLE
Control scroll for avatar list 

### ISSUE THREAD

**Issue by Adil7767** [birdwingo/react-native-instagram-stories#88]
i want to show just 2 or more item in fixed width and don't want scroll  so there should be boolean option for scroll enabled 
secondly  there should be horizontal and vertical scroll option
if any one can update the package please do ASAP
Thank You

**Comment by LukasFridmansky** [comment]
Hi, you should be able to control that with listContainerProps

**Comment by Adil7767** [comment]
> Hi, you should be able to control that with listContainerProps

thanks for quick reply let me now how i can do that

**Comment by LukasFridmansky** [comment]
Can you use `avatarListContainerProps` instead? `listContainerProps` is depracated and will be removed soon, `avatarListContainerProps` will work the same way. Thank you
