### ISSUE TITLE
When pressed image of a person inside render story model, How can i navigate if i have userID based on each user story ?

### ISSUE THREAD

**Issue by Ahsanali012** [birdwingo/react-native-instagram-stories#93]
I have my following code , My question is how can i press user image which is imageURL to navigate to my custom made screen as scenario is to show user profile. As we have story.id which works as userID 

`
  if (AllStoriesPosts && AllStoriesPosts.length > 0) {
    InstaStories = AllStoriesPosts.map((story) => ({
      id: story.id,
      name: story.name,
      imgUrl: story?.imgUrl,

      stories: story.stories.map((item) => {
        let mediaType: "video" | "image" | undefined;
        if (item.mediaType === "video" || item.mediaType === "image") {
          mediaType = item.mediaType;
        }
        return {
          id: item.id,
          mediaType: mediaType,
          sourceUrl: item.sourceUrl,
          renderContent: () => storyContent(item, story.id),
        };
      }),
    }));
  }
`

**Comment by LukasFridmansky** [comment]
First of all, do you mean pressing user image in stories list or in story modal header? Secondly, you can't do that with current logic. The only thing you can do use renderAvatar or renderStoryHeader for story modal header. In that case you will need to handle styles and everything. But, if you describe what exactly you have in mind, I could add maybe some new properties

**Comment by Ahsanali012** [comment]
> First of all, do you mean pressing user image in stories list or in story modal header? Secondly, you can't do that with current logic. The only thing you can do use renderAvatar or renderStoryHeader for story modal header. In that case you will need to handle styles and everything. But, if you describe what exactly you have in mind, I could add maybe some new properties

In stories modal when stories on click modal appears and we have the story header with image , name

**Comment by LukasFridmansky** [comment]
Hey, you can add onStoryHeaderPress callback to every user, check [README](https://github.com/birdwingo/react-native-instagram-stories?tab=readme-ov-file#instagramstoryprops)

**Comment by Ahsanali012** [comment]
> Hey, you can add onStoryHeaderPress callback to every user, check [README](https://github.com/birdwingo/react-native-instagram-stories?tab=readme-ov-file#instagramstoryprops)

Thanks I'll try and let you know soon
