### ISSUE TITLE
When click on back to goToPreviousStory it doesn't go to the 1st story. that last we can view to the 2nd story

### ISSUE THREAD

**Issue by jazzylamba** [birdwingo/react-native-instagram-stories#94]

**Comment by LukasFridmansky** [comment]
Hey! Can you please provide video o code snippet? For me the goToPreviousStory method works as supposed. Thank you.

**Comment by jazzylamba** [comment]
https://github.com/user-attachments/assets/f58f9883-4de1-404f-a05b-7d7f54fb69f5

@LukasFridmansky Here i recorded the video. when i click right it jumps to next story but when i click left to see back story then it backs to 2 story. unable to view the first one

**Comment by LukasFridmansky** [comment]
Can you please send me your code? Especially the data you are passing to stories

**Comment by jazzylamba** [comment]
Here is my code @LukasFridmansky 

import InstagramStories from '@birdwingo/react-native-instagram-stories';
import React, {forwardRef, useContext, useEffect, useImperativeHandle, useRef, useState} from 'react';
import {StyleSheet, View} from 'react-native';
import {size} from 'react-native-responsive-sizes';
import {AuthContext} from '../../../contexts/AuthContext';
import {getAPIEndpointUrl} from '../../../utilities/RequestHelper';
import { isUrl } from '../../../utilities/functions';
import { createAxiosInstance } from '../../../utilities/AxiosRequest';

const StoriesModal = forwardRef(({data, hideDisplay, isVisible}, ref) => {
  const {user, token} = useContext(AuthContext);
  const [urls, setUrls] = useState([]);
  const instance = createAxiosInstance(token);

  const instagramStoriesRef = useRef(null);

  useEffect(() => {
    const fetchImageUrls = async () => {
      try {
        const promises = data.map(async (image) => {
          if(image.thumbnail.includes('/uploads/stories/')){
            return getAPIEndpointUrl() + image.thumbnail;
          }else{
            const toks = image.thumbnail.split('/uploads/');
            const response = await instance.get('/auth-s3/signed-image-link', {
              params: {fileName: toks[toks.length-1]}
            });
            return response.data.url;
          }
        });

        const urls = await Promise.all(promises);
        setUrls(urls);
      } catch (error) {
        console.error('Error fetching image URLs:', error);
        setError('Error fetching image URLs');
      } finally {
        setLoading(false);
      }
    };

    if (data.length > 0) {
      fetchImageUrls();
    }
  }, [data]);

  const getStories = () => {
    return (
      data &&
      data?.map((item, index) => {
        return {
          id: index,
          source: {
            uri: urls[index],
          },
        };
      })
    );
  };

  let userStoriesData = [
    {
      id: user?.userId,
      imgUrl: isUrl(user?.avatar) ? user?.avatar : `${getAPIEndpointUrl()}${user?.avatar}`,
      name: user?.fullName,
      stories: getStories(),
    },
  ];

  // Expose the setStories method to the parent component
  useImperativeHandle(ref, () => ({
    // setStories: () => instagramStoriesRef.current?.setStories(userStoriesData),
    show: (id) => {instagramStoriesRef.current?.show(id)}
  }));

  return (
    <View style={styles.gradientBorder}>
      {urls.length ? (
        <InstagramStories
        ref={instagramStoriesRef}
        isVisible={isVisible}
        stories={userStoriesData}
        // saveProgress={true}
        avatarBorderColors={['#FBAA47', '#D91A46', '#D91A46','#A60F93','#A60F93',]}
        avatarSeenBorderColors={[
          '#F7B801',
          '#F18701',
          '#F35B04',
          '#F5301E',
          '#C81D4E',
          '#8F1D4E',
        ]}
        closeIconColor={'white'}
        avatarListContainerStyle={[styles.hollowCircle]}
        avatarSize={73}
        animationDuration={5000}
        hideElementsOnLongPress={true}
        progressColor={'gray'}
        textStyle={{color: 'white'}}
        hideAvatarList={hideDisplay}
        avatarListContainerProps={{scrollEnabled: false}}
      />
      ) : null}
      
    </View>
  );
})

const styles = StyleSheet.create({
  gradientBorder: {
    width: 100,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  hollowCircle: {
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default StoriesModal;

**Comment by jazzylamba** [comment]
@LukasFridmansky No there is a function exists but for now i am not using this to show stories . i am using 
`isVisible={isVisible}` this prop to show the stories

**Comment by LukasFridmansky** [comment]
I mean this:
```
const getStories = () => {
    return (
      data &&
      data?.map((item, index) => {
        return {
          id: index, // THIS MUST BE STRING !!!
          source: {
            uri: urls[index],
          },
        };
      })
    );
  };
```

**Comment by jazzylamba** [comment]
Yeah. Thanks solve my issue @LukasFridmansky ❤️
