### ISSUE TITLE
Looping Through User Stories

### ISSUE THREAD

**Issue by Adil7767** [birdwingo/react-native-instagram-stories#99]
**Current Behavior:**

The modal moves to the next user's stories when the current story ends.
If there are no more stories, the modal hides.

**Expected Behavior:**

When the last story of the current user ends, it should start replaying stories from the first index of the same user.

**Steps to Reproduce:**

Open the stories modal.
Navigate to the last story of the current user.
Observe the behavior when the last story ends

**Possible Solution:**

Implement a check to detect when the current story is the last one.
If it is the last story, reset the story index to 0 and replay the stories from the beginning.
or
add a prop like `looping={true/false} ` default false
if provide true then give expected behavior

**Comment by LukasFridmansky** [comment]
Hey, thank you for you idea. I will implement as soon as possible

**Comment by Adil7767** [comment]
can we create this effect for now
any suggestion

**Comment by LukasFridmansky** [comment]
Am I understand it correctly? You want have looping only for last user? So when last story of last user ends you want show first story of current user, not first user, right?

**Comment by Adil7767** [comment]
yes i want if a single user then start looping of stories
